/* ==========================================================================
   V2: Nâng cấp hệ thống Đa chi nhánh & Quản lý kho (Mô hình 5-6 cửa hàng)
   ========================================================================== */

-- 1. TẠO BẢNG CỬA HÀNG (STORES)
-- --------------------------------------------------------------------------
CREATE TABLE public.stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    address character varying(255) NOT NULL,
    phone character varying(15),
    is_active boolean DEFAULT true,
    created_at timestamp(6) without time zone DEFAULT now(),
    updated_at timestamp(6) without time zone DEFAULT now()
);

-- 2. KHỞI TẠO DỮ LIỆU 6 CỬA HÀNG MẪU
-- --------------------------------------------------------------------------
INSERT INTO public.stores (name, address, phone) VALUES 
('Coffee House - Cầu Giấy', '123 Cầu Giấy, Hà Nội', '0988111111'),      -- ID: 1
('Coffee House - Hoàn Kiếm', '99 Hàng Bài, Hà Nội', '0988222222'),     -- ID: 2
('Coffee House - Hà Đông', '10 Quang Trung, Hà Nội', '0988333333'),    -- ID: 3
('Coffee House - Quận 1', '25 Nguyễn Huệ, TP.HCM', '0909444444'),      -- ID: 4
('Coffee House - Bình Thạnh', '30 Đường D2, TP.HCM', '0909555555'),    -- ID: 5
('Coffee House - Đà Nẵng', '15 Bạch Đằng, Đà Nẵng', '0935666666');     -- ID: 6

-- 3. NÂNG CẤP BẢNG ĐƠN HÀNG (ORDERS)
-- Gắn đơn hàng vào cửa hàng cụ thể
-- --------------------------------------------------------------------------
ALTER TABLE public.orders ADD COLUMN store_id bigint;

-- Quan trọng: Gán toàn bộ đơn hàng cũ (nếu có) cho Cửa hàng 1 (Cầu Giấy)
-- để tránh lỗi dữ liệu null
UPDATE public.orders SET store_id = 1 WHERE store_id IS NULL;

-- Sau khi update xong mới set NOT NULL và khóa ngoại
ALTER TABLE public.orders ALTER COLUMN store_id SET NOT NULL;
ALTER TABLE public.orders ADD CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES public.stores(id);


-- 4. NÂNG CẤP BẢNG USER (NHÂN VIÊN)
-- Nhân viên thuộc cửa hàng nào? (Admin có thể null store_id)
-- --------------------------------------------------------------------------
ALTER TABLE public.users ADD COLUMN store_id bigint;
ALTER TABLE public.users ADD CONSTRAINT fk_users_store FOREIGN KEY (store_id) REFERENCES public.stores(id);

-- (Tùy chọn) Gán user đang có role STAFF vào Cửa hàng 1
UPDATE public.users SET store_id = 1 WHERE role = 'STAFF';


-- 5. TÁCH TỒN KHO RA KHỎI BIẾN THỂ SẢN PHẨM (PRODUCT_STOCKS)
-- Mỗi cửa hàng sẽ có số lượng tồn kho riêng cho từng sản phẩm
-- --------------------------------------------------------------------------
CREATE TABLE public.product_stocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id bigint NOT NULL,
    store_id bigint NOT NULL,
    quantity integer DEFAULT 0 CHECK (quantity >= 0), -- Không cho phép âm kho
    last_updated timestamp(6) without time zone DEFAULT now(),
    
    CONSTRAINT fk_stock_variant FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id),
    CONSTRAINT fk_stock_store FOREIGN KEY (store_id) REFERENCES public.stores(id),
    -- Đảm bảo mỗi sản phẩm ở 1 quán chỉ có 1 dòng dữ liệu kho duy nhất
    CONSTRAINT uk_variant_store UNIQUE (product_variant_id, store_id) 
);


-- 6. DI TRÚ DỮ LIỆU TỒN KHO (DATA MIGRATION)
-- Lấy số lượng tồn kho cũ, chia đều hoặc gán cho các cửa hàng mới
-- --------------------------------------------------------------------------

-- Cách 1: Gán tồn kho hiện tại cho Cửa hàng 1 (Cầu Giấy)
INSERT INTO public.product_stocks (product_variant_id, store_id, quantity)
SELECT id, 1, stock_quantity FROM public.product_variants;

-- Cách 2: Khởi tạo Cửa hàng 2 & 3 với số lượng = 0 (để sẵn sàng nhập hàng)
INSERT INTO public.product_stocks (product_variant_id, store_id, quantity)
SELECT id, 2, 0 FROM public.product_variants;

INSERT INTO public.product_stocks (product_variant_id, store_id, quantity)
SELECT id, 3, 0 FROM public.product_variants;


-- 7. XỬ LÝ CỘT STOCK CŨ
-- Đổi tên cột cũ để code Java biết không được dùng nó làm nguồn chính nữa
-- (Có thể xóa đi sau này, nhưng hiện tại giữ lại để tham khảo hoặc làm cache tổng)
-- --------------------------------------------------------------------------
ALTER TABLE public.product_variants RENAME COLUMN stock_quantity TO stock_quantity_legacy_do_not_use;


-- 8. TẠO BẢNG LỊCH SỬ KHO ĐƠN GIẢN (STOCK_HISTORY)
-- Ghi lại mọi biến động: Bán hàng, Nhập hàng, Hủy hàng...
-- --------------------------------------------------------------------------
CREATE TABLE public.stock_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id bigint NOT NULL,
    store_id bigint NOT NULL,
    quantity_changed integer NOT NULL, -- Ví dụ: +50 (Nhập), -2 (Bán)
    current_quantity integer NOT NULL, -- Tồn kho tại thời điểm đó (Snapshot)
    reason character varying(50) NOT NULL, -- SALE, IMPORT, ADJUSTMENT
    note text,
    created_by bigint, -- User ID thực hiện
    created_at timestamp(6) without time zone DEFAULT now(),
    
    CONSTRAINT fk_history_variant FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id),
    CONSTRAINT fk_history_store FOREIGN KEY (store_id) REFERENCES public.stores(id)
);